# non geOrchestra images
database:
  image: georchestra/database
  environment:
    - POSTGRES_USER=georchestra
    - POSTGRES_PASSWORD=georchestra
  volumes:
    - postgresql_data:/var/lib/postgresql/data

ldap:
  image: georchestra/ldap
  environment:
      - SLAPD_ORGANISATION=georchestra
      - SLAPD_DOMAIN=georchestra.org
      - SLAPD_PASSWORD=secret
      - SLAPD_ADDITIONAL_MODULES=groupofmembers
  volumes:
    - ldap_data:/var/lib/ldap
    - ldap_config:/etc/ldap

smtp:
  image: camptocamp/smtp-sink

courier-imap:
  image: camptocamp/courier-imap
  volumes_from:
    - smtp:rw

webmail:
  image: camptocamp/sqwebmail
  ports:
    - "8081:80"
  volumes_from:
    - smtp:rw

geodata:
  image: georchestra/ssh_data
  ports:
    - "2222:22"
  volumes:
    - geoserver_geodata:/home/geoserver/data

# geOrchestra images
    
geoserver:
  image: georchestra/geoserver:latest
  volumes:
    - geoserver_datadir:/var/local/geoserver
    - geoserver_geodata:/var/local/geodata
    - geoserver_tiles:/var/local/tiles
  links:
    - database
    - ldap
  environment:
    - XMX=2g

geowebcache:
  image: georchestra/geowebcache:latest
  volumes:
    - geowebcache_tiles:/var/local/tiles
  environment:
    - XMX=1g

proxy:
  image: georchestra/security-proxy:latest
  ports:
    - "8080:8080"
  links:
    - database
    - ldap
    - cas
    - mapfishapp
    - extractorapp
    - ldapadmin
    - geonetwork
    - header
    - geoserver
    - analytics
    - catalogapp
    - downloadform
  environment:
    - XMX=1g

cas:
  image: georchestra/cas:latest
  links:
    - ldap
  environment:
    - XMX=1g

mapfishapp:
  image: georchestra/mapfishapp:latest
  volumes:
    - mapfishapp_uploads:/var/local/uploads
  links:
    - database
  volumes:
    - mapfishapp_uploads:/var/local/uploads
  environment:
    - XMX=1g

extractorapp:
  image: georchestra/extractorapp:latest
  volumes:
    - extractorapp_extracts:/var/local/extracts
  links:
    - database
    - smtp
  volumes:
    - extractorapp_extracts:/var/local/extracts
  environment:
    - XMX=1g

header:
  image: georchestra/header:latest
  environment:
    - XMX=512m

ldapadmin:
  image: georchestra/ldapadmin:latest
  links:
    - database
    - ldap
    - smtp
  environment:
    - XMX=1g

geonetwork:
  image: georchestra/geonetwork:3-latest
  ports:
    - "1099:1099"
  links:
    - database
    - ldap
  volumes:
    - geonetwork_datadir:/var/local/geonetwork
  environment:
    - XMX=2g

analytics:
  image: georchestra/analytics:latest
  links:
    - database
  environment:
    - XMX=512m

catalogapp:
  image: georchestra/catalogapp:latest

downloadform:
  image: georchestra/downloadform:latest
